### PR TITLE
Add dateFormat option

### PR DESCRIPTION
**Pull request by welcoMattic**
Ref. https://github.com/themsaid/katana/issues/15

### CODE REVIEW

**Comment by themsaid** [comment]
Hmm, why don't you use the day format you want directly in the page? There's no specific requirements for the date format there.

**Comment by welcoMattic** [comment]
I can't use it in blog post template, because `@yield(post::date)` can't be modified with `date()` function

**Comment by themsaid** [comment]
I mean why not use the format you need directly while declaring the section? It's only a string, you can type the date in whatever format you want.

**Comment by welcoMattic** [comment]
Yes of course, but it can be useful to validate the date format.
In my case, posts come from Jekyll, and the date data have to be formatted, so I prefer add date format feature in Katana core than re-write all my date on all my posts.

But, if this case is too special, feel free to close issue, and reject PR ;)

**Pull request closed without merging**
